### PR TITLE
Fixes issue #5

### PR DESCRIPTION
**Pull request by canaryGrapher**
Fixes issue number #5. Added custom modal component instead of browser prompt
image

### CODE REVIEW

**Comment by alammoiz** [comment]
This issue was assigned to me. I'm working on it @canaryGrapher 
CC: @tanmayVaish

**Review by tanmayVaish — COMMENTED** [review]
@canaryGrapher , @alammoiz already got assigned to this issue. I have to close this PR!!

**Comment by tanmayVaish** [comment]
@canaryGrapher Sorry for the inconvenience, but the guy assigned to #5 just copied your code. So, I welcome you to reopen your PR and proceed!

**Comment by canaryGrapher** [comment]
Sure thing. ✌🏾

**Comment by alammoiz** [comment]
> @canaryGrapher Sorry for the inconvenience, but the guy assigned to #5 just copied your code. So, I welcome you to reopen your PR and proceed!

I have taken an idea from this PR, also I have make changes in modal component to make it reusable like heading and description. Please don't mark spam 

Please @tanmayVaish

**Comment by alammoiz** [comment]
I'm requesting you to remove the spam tag from my PR @tanmayVaish

**Pull request closed without merging**
